# Generated by Django 2.2.17 on 2021-01-28 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_contact_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='date',
        ),
    ]
