# Generated by Django 2.2.17 on 2021-01-28 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_contact_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Adr',
            new_name='adr',
        ),
    ]
